apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swarmforge.fullname" . }}
  labels:
    {{- include "swarmforge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "swarmforge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swarmforge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swarmforge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: ws
              containerPort: 8081
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.redisPort | quote }}
            - name: GRPC_PORT
              value: "50051"
            - name: WORLD_WIDTH
              value: "500"
            - name: WORLD_HEIGHT
              value: "100"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
