{{- if .Values.ingress.enabled -}}
{{- $fullName := include "swarmforge.fullname" . -}}
{{- $serverName := include "swarmforge.server.fullname" . -}}
{{- $webName := include "swarmforge.web.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "swarmforge.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if eq .service "web" }}{{ $webName }}{{ else }}{{ $serverName }}{{ end }}
                port:
                  number: {{ if eq .service "web" }}{{ $.Values.web.service.port }}{{ else }}{{ $.Values.server.service.httpPort }}{{ end }}
          {{- end }}
    {{- end }}
{{- end }}
