apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swarmforge.fullname" . }}-secret
  labels:
    {{- include "swarmforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.password | quote }}{{ else }}{{ .Values.externalDatabase.password | quote }}{{ end }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
