apiVersion: v1
kind: Service
metadata:
  name: {{ include "swarmforge.server.fullname" . }}
  labels:
    {{- include "swarmforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.server.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swarmforge.server.selectorLabels" . | nindent 4 }}
