apiVersion: v1
kind: Service
metadata:
  name: {{ include "swarmforge.fullname" . }}
  labels:
    {{- include "swarmforge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "swarmforge.selectorLabels" . | nindent 4 }}
