/*
 * SwarmForge - Eusocial Insect Simulation
 * Copyright (c) 2022-2026 Silvère Martin-Michiellot
 * AI Assistant: Gemini (Google DeepMind)
 * MIT License
 */
package org.swarmforge.core.simulation;

/**
 * Social Thermoregulation System (Formica Wood Ants & Apis Honeybees).
 * Simulates collective endothermic heating (flight muscle isometric contraction/shivering)
 * and active entrance fanning for evaporative cooling to maintain homeostatic brood temperature (34.5°C).
 *
 * @author Silvère Martin-Michiellot
 * @author Gemini AI Assistant
 */
public class SocialThermoregulationSystem {

    public static final float IDEAL_BROOD_TEMP = 34.5f;

    /**
     * Calculates thermal output (joules/tick) generated by a cluster of shivering workers during cold ambient drops.
     */
    public static float calculateEndothermicHeatOutput(int shiveringWorkers, float ambientTemp) {
        if (ambientTemp >= IDEAL_BROOD_TEMP) return 0.0f;
        float tempDeficit = IDEAL_BROOD_TEMP - ambientTemp;
        // Each worker generates up to 0.05°C thermal delta per tick when shivering
        return Math.min(tempDeficit, shiveringWorkers * 0.05f);
    }

    /**
     * Calculates cooling airflow generated by fanning workers at nest entrances during hot ambient spikes.
     */
    public static float calculateFanningCoolingOutput(int fanningWorkers, float ambientTemp) {
        if (ambientTemp <= IDEAL_BROOD_TEMP) return 0.0f;
        float tempSurplus = ambientTemp - IDEAL_BROOD_TEMP;
        return Math.min(tempSurplus, fanningWorkers * 0.08f);
    }
}
